elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: logstash
  volumes:
    - logstash-conf:/config-dir
    #- /etc/nginx/ssl/certs/iplantcollaborative.org.chained.crt:/etc/ssl/iplant.crt
    #- iplantcollaborative.key:/etc/ssl/iplant.key
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
  volumes_from: 
    - iplant_data
  command: logstash -f /config-dir/logstash.conf
kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
